import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar, Footer } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <Navbar />
          <div className="max-w-container mx-auto mt-lg">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
