import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar, Footer } from "@/components";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <Navbar />
          <Suspense
            fallback={
              <div className="flex items-center justify-center min-h-screen">
                <div className="text-center">
                  <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600 mx-auto mb-4"></div>
                  <p className="text-xl text-gray-600">Loading...</p>
                </div>
              </div>
            }
          >
            <div className="max-w-container mx-auto mt-lg">{children}</div>
          </Suspense>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
